# Generated by Django 4.0.5 on 2022-10-28 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagField', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='discussion',
            old_name='discussion',
            new_name='discussionField',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='tag',
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussions.discussion')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussions.tag')),
            ],
        ),
        migrations.AddField(
            model_name='discussion',
            name='tags',
            field=models.ManyToManyField(blank=True, to='discussions.tag'),
        ),
    ]
