# Generated by Django 4.1.2 on 2022-10-28 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "discussions",
            "0002_tag_rename_discussion_discussion_discussionfield_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="discussion", name="tags",),
    ]
